version: "3"  

tasks:  
  default: # Если не указать конкретную команду, будут выполнены дефолтные
    cmds:  
      - task: migrate  
  migrate:  ## Команда для миграции
    desc: "Run database migrations"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/storage.db --migrations-path=./migrations
  start: ##команда
    desc: "Run project"
    cmds:
    - go run ./cmd/url-shortener
  consumer:
    desc: "Run consumer"
    cmds:
    - go run ./cmd/consumer 
  producer:
    desc: "Run producer"
    cmds:
    - go run ./cmd/producer